platform :ios, ‘7.0’

target :SuperDownLoad do

pod 'SDWebImage', '~> 3.7.6'

pod 'SSZipArchive', '~> 1.2'

pod 'AFNetworking', '~> 3.1.0'

pod 'Masonry', '~> 1.0.0'

pod 'MJExtension', '~> 3.0.10'

pod 'SVProgressHUD', '~> 2.0.3'

pod 'RESideMenu', '~> 4.0.7'

end